
'use client';
import { useState } from 'react';
import { scenes } from '@/lib/scenes';
export default function Home(){
 const [file,setFile]=useState<File|null>(null); const [sceneId,setSceneId]=useState('restaurant'); const [loading,setLoading]=useState(false); const [previews,setPreviews]=useState<string[]>([]); const [orderId,setOrderId]=useState(''); const [inputUrl,setInputUrl]=useState(''); const [error,setError]=useState('');
 async function generate(){if(!file){setError('Please upload a pet photo first.');return} setLoading(true);setError('');setPreviews([]); const fd=new FormData(); fd.append('file',file);fd.append('sceneId',sceneId); const res=await fetch('/api/generate',{method:'POST',body:fd}); const data=await res.json(); setLoading(false); if(!res.ok){setError(data.error||'Preview generation failed.');return} setPreviews(data.previewUrls||[]);setOrderId(data.orderId);setInputUrl(data.inputUrl)}
 async function pay(packageType:'basic'|'premium'){const res=await fetch('/api/create-payment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderId,packageType,inputUrl,sceneId})}); const data=await res.json(); if(data.checkoutUrl)window.location.href=data.checkoutUrl; else setError(data.error||'Payment could not be created.')}
 return <main className="page"><div className="wrap"><header className="header"><div className="brand"><div className="logo">🐾</div>PetLanda</div><a className="btn gold" href="#create">Create Pet Art</a></header><section className="hero"><h1>Place your pet into magical scenes</h1><p>Upload your real pet and create 3 low-resolution previews. Unlock 5 or 10 unique HD images after payment.</p></section><section className="grid2" id="create"><div className="panel"><h2>1. Upload your pet</h2><div className="uploadbox"><div><input type="file" accept="image/*" onChange={(e)=>setFile(e.target.files?.[0]||null)}/><p>{file?file.name:'Choose a clear photo of your pet'}</p></div></div></div><div className="panel"><h2>2. Choose a scene</h2><div className="scenes">{scenes.map(s=><button key={s.id} className={`scene ${sceneId===s.id?'active':''}`} onClick={()=>setSceneId(s.id)}><div className="scene-img" style={{background:s.sampleBg}}>{s.sampleAnimal}</div><div className="scene-body"><div className="scene-title">{s.emoji} {s.title}</div><div className="scene-sub">{s.subtitle}</div></div></button>)}</div></div></section><section className="panel" style={{marginTop:22,textAlign:'center'}}><h2>3. Create 3 free previews</h2><p className="small">These small watermarked previews show variation in scene, angle and mood.</p>{error&&<div className="error">{error}</div>}<button className="btn gold" onClick={generate} disabled={loading}>{loading?'Creating previews...':'Create my free previews'}</button>{previews.length>0&&<><div className="preview-grid">{previews.map((p,i)=><img key={i} src={p} alt={`Preview ${i+1}`}/>)}</div><h2>Unlock your full HD pack</h2><div className="packs"><div className="pack"><h3>Basic Pack</h3><div className="price">€7.99</div><p>5 unique HD images without watermark.</p><button className="btn" onClick={()=>pay('basic')}>Unlock 5 HD images</button></div><div className="pack"><h3>Premium Pack</h3><div className="price">€14.99</div><p>10 unique HD images with more variation.</p><button className="btn gold" onClick={()=>pay('premium')}>Unlock 10 HD images</button></div></div></>}</section></div></main>
}
